import './global.css';

export const metadata = {
  title: 'Welcome to youx-front',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className='fixed inset-0'>{children}</body>
    </html>
  );
}
